version: '3'
services:
  minecraft-forge:
    image:  minecraft-server-forge:1.0.1
    ports:
      - "25565:25565"
    volumes:
      - ./minecraft:/minecraft
    environment:
      - FORGE_VERSION=1.18-38.0.17
      - MAX_RAM=12G
      - MIN_RAM=6G
      - SEED=
volumes:
  minecraft: 