version: '3'
services:
  minecraft-forge:
    image: minecraft-server-forge:1.0.3
    ports:
      - "25565:25565"
      - "25575:25575"
    volumes:
      - ./minecraft:/minecraft
    environment:
      - FORGE_VERSION=1.18.2-40.2.0
      - MAX_RAM=6G
      - MIN_RAM=6G
      - SEED=
      - MOTD=§A§L§NServer §6§N§nMinecraft §M§L§NForge
      - DIFFICULTY=3 
volumes:
  minecraft:  